name: sheipados-nutrition-api

services:
  db:
    container_name: sheipados-db
    image: mysql:5.7
    restart: always
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sheipados_db
      MYSQL_PASSWORD: root
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - mysql-phpmyadmin

  # app:
  #   container_name: sheipados-api
  #   build: .
  #   ports:
  #     - '3000:3000'
  #   depends_on:
  #     - db
  #   env_file: .env
  #   networks:
  #     - mysql-phpmyadmin

  phpmyadmin:
    container_name: phpmy-admin
    image: phpmyadmin/phpmyadmin:latest
    links:
      - db
    ports:
      - 80:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    networks:
      - mysql-phpmyadmin

networks:
  mysql-phpmyadmin:

volumes:
  db_data: